apiVersion: v1
kind: Service
metadata:
  name: open5gs-hss
  namespace: open5gs
  labels:
    epc-mode: hss
spec:
  selector:
    epc-mode: hss
  ports:
  - protocol: SCTP
    name: sctp  
    port: 3868    
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-hss-deployment
  labels:
    epc-mode: hss
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: hss
  template:
    metadata:    
      labels:
        epc-mode: hss
    spec:
      containers:
        - name: hss
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - sleep 10;
            open5gs-hssd -c /open5gs/config-map/hss.yaml
          volumeMounts:
          - name: open5gs-hss-config
            mountPath: /open5gs/config-map/hss.yaml
            subPath: "hss.yaml"
          - name: open5gs-hss-diameter
            mountPath: /open5gs/config-map/diameter-hss.conf
            subPath: "diameter-hss.conf"            
          - mountPath: "/open5gs/diameter-ca/"
            name: diameter-ca
          - mountPath: "/open5gs/tls/"
            name: hss-tls                   
      volumes:
        - name: open5gs-hss-config
          configMap:
            name: open5gs-hss-config
        - name: open5gs-hss-diameter
          configMap:
            name: open5gs-hss-diameter           
        - name: diameter-ca
          secret:
            secretName: {{ .Values.diameter.caSecretName }}  
        - name: hss-tls
          secret:
            secretName: {{ .Values.hss.tlsSecretName }}                                               
