apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-mme-1-config
  namespace: open5gs
  labels:
    epc-mode: mme
data:
  mme.yaml: |
    logger:
        file: /var/log/open5gs/mme.log

    parameter:

    mme:
        freeDiameter: /open5gs/config-map/diameter-mme.conf
        s1ap:
           dev: eth0
        gtpc:
           dev: eth0
        gummei:
          plmn_id:
            mcc: {{ .Values.mme.mcc }}
            mnc: {{ .Values.mme.mnc }}
          mme_gid: 2
          mme_code: 1
        tai:
          plmn_id:
            mcc: {{ .Values.mme.mcc }}
            mnc: {{ .Values.mme.mnc }}
          tac: {{ .Values.mme.tac }}
        security:
            integrity_order : [ EIA1, EIA2, EIA0 ]
            ciphering_order : [ EEA0, EEA1, EEA2 ]
        network_name:
            full: Open5GS
        mme_name: open5gs-mme1

    sgwc:
        gtpc:
          - name: open5gs-sgwc
    smf:
      gtpc:
        - name: open5gs-smf
    metrics:
        addr: 0.0.0.0
        port: 9090        
