apiVersion: v1
kind: Service
metadata:
  name: open5gs-mme-1
  namespace: open5gs
  labels:
    epc-mode: mme-1
spec:
  selector:
    epc-mode: mme-1
  ports:
  - protocol: SCTP
    name: sctp  
    port: 3868    
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-mme-1-deployment
  namespace: open5gs
  labels:
    epc-mode: mme-1
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: mme-1
  template:
    metadata:
      annotations:
        "cni.projectcalico.org/ipAddrs": "[\"{{ .Values.mme.amfOneIP }}\"]"     
      labels:
        epc-mode: mme-1
        mme-svc: general
    spec:
      containers:
      - name: mme
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        securityContext:
          privileged: true        
        command: ["/bin/sh", "-c"]
        args:
        - sleep 10;
          apt-get update;apt-get install tcpdump inetutils-ping arptables -y;
          ip link set up tunl0;
          ip addr add 172.18.0.103 dev tunl0;
          sysctl w net.ipv4.conf.tunl0.rp_filter=0;
          arptables -A IN -d 172.18.0.103 -j DROP;
          arptables -A OUT -s 172.18.0.103 -j mangle --mangle-ip-s {{ .Values.mme.amfOneIP }};
          open5gs-mmed -c /open5gs/config-map/mme.yaml
        volumeMounts:
        - name: open5gs-mme-config
          mountPath: /open5gs/config-map/mme.yaml
          subPath: "mme.yaml"
        - name: open5gs-mme-diameter
          mountPath: /open5gs/config-map/diameter-mme.conf
          subPath: "diameter-mme.conf"
        - mountPath: "/open5gs/diameter-ca/"
          name: diameter-ca
        - mountPath: "/open5gs/tls/"
          name: mme-tls         
      volumes:
        - name: open5gs-mme-config
          configMap:
            name: open5gs-mme-1-config
        - name: open5gs-mme-diameter
          configMap:
            name: open5gs-mme-1-diameter
        - name: diameter-ca
          secret:
            secretName: {{ .Values.diameter.caSecretName }}  
        - name: mme-tls
          secret:
            secretName: {{ .Values.mme.tlsSecretName }}                
