apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcrf
  namespace: open5gs
  labels:
    epc-mode: pcrf
spec:
  selector:
    epc-mode: pcrf
  ports:
  - protocol: SCTP
    name: sctp  
    port: 3868    
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-pcrf-deployment
  namespace: open5gs
  labels:
    epc-mode: pcrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: pcrf
  template:
    metadata:   
      labels:
        epc-mode: pcrf
    spec:      
      containers:
        - name: pcrf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - sleep 10;
            open5gs-pcrfd -c /open5gs/config-map/pcrf.yaml
          volumeMounts:
          - name: open5gs-pcrf-config
            mountPath: /open5gs/config-map/pcrf.yaml
            subPath: "pcrf.yaml"
          - name: open5gs-pcrf-diameter
            mountPath: /open5gs/config-map/diameter-pcrf.conf
            subPath: "diameter-pcrf.conf"
          - mountPath: "/open5gs/diameter-ca/"
            name: diameter-ca
          - mountPath: "/open5gs/tls/"
            name: pcrf-tls                                    
      volumes:
        - name: open5gs-pcrf-config
          configMap:
            name: open5gs-pcrf-config
        - name: open5gs-pcrf-diameter
          configMap:
            name: open5gs-pcrf-diameter       
        - name: diameter-ca
          secret:
            secretName: {{ .Values.diameter.caSecretName }}    
        - name: pcrf-tls
          secret:
            secretName: {{ .Values.pcrf.tlsSecretName }}                 
