apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwu
  namespace: open5gs
  labels:
    epc-mode: sgwu
spec:
  clusterIP: None
  selector:
    epc-mode: sgwu
  ports:
  - protocol: UDP
    name: gtpu  
    port: 2152     
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-sgwu-deployment
  namespace: open5gs   
  labels:
    epc-mode: sgwu
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: sgwu
  template:
    metadata:
      labels:
        epc-mode: sgwu
    spec:   
      containers:
      - name: sgwu
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - open5gs-sgwud -c /open5gs/config-map/sgwu.yaml;
        volumeMounts:
          - name: open5gs-sgwu-config
            mountPath: /open5gs/config-map/sgwu.yaml
            subPath: "sgwu.yaml"              
      volumes:
        - name: open5gs-sgwu-config
          configMap:
            name: open5gs-sgwu-config
