apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf
  namespace: open5gs
  labels:
    epc-mode: smf
spec:
  clusterIP: None
  selector:
    epc-mode: smf
  ports:
  - protocol: UDP
    name: pfcp
    port: 8805
  - protocol: TCP
    name: sbi
    port: 80     
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf-diameter
  namespace: open5gs
  labels:
    epc-mode: smf
spec:
  selector:
    epc-mode: smf
  ports:
  - protocol: SCTP
    name: sctp  
    port: 3868
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-smf-deployment
  namespace: open5gs
  labels:
    epc-mode: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: smf
  template:
    metadata:      
      labels:
        epc-mode: smf
    spec:          
      containers:
      - name: smf
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        ports:
        - containerPort: 3868
          hostIP: 10.0.0.244
          hostPort: 3868
          protocol: SCTP
        command: ["/bin/sh", "-c"]
        args:
        - sleep 10;         
          open5gs-smfd -c /open5gs/config-map/smf.yaml;
        volumeMounts:
          - name: open5gs-smf-config
            mountPath: /open5gs/config-map/smf.yaml
            subPath: "smf.yaml"
          - name: open5gs-smf-diameter
            mountPath: /open5gs/config-map/diameter-smf.conf
            subPath: "diameter-smf.conf"            
          - mountPath: "/open5gs/diameter-ca/"
            name: diameter-ca
          - mountPath: "/open5gs/tls/"
            name: smf-tls                                         
      volumes:
        - name: open5gs-smf-config
          configMap:
            name: open5gs-smf-config
        - name: open5gs-smf-diameter
          configMap:
            name: open5gs-smf-diameter
        - name: diameter-ca
          secret:
            secretName: {{ .Values.diameter.caSecretName }}   
        - name: smf-tls
          secret:
            secretName: {{ .Values.smf.tlsSecretName }}                   
