apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log
        #level: debug

    parameter:
        no_ipv6: true

    smf:
        sbi:
           dev: eth0
        gtpc:
           dev: eth0
        gtpu:
           dev: eth0           
        pfcp:
           dev: eth0
        subnet:
         - addr: 10.45.0.1/16
           apn: {{ .Values.apn }}
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400
        freeDiameter: /open5gs/config-map/diameter-smf.conf

    nrf:
     sbi:
      - name: 
        - open5gs-nrf-svc-pool
        port: 7777

    upf:
      pfcp:
       - name: open5gs-upf
         apn: {{ .Values.apn }}