version: "3.9"
   
services:
  mme-lb:
      container_name: "mme-lb"
      tty: true
      image: ubuntu:focal
      privileged: true
      command: >
        sh -c  "apt-get update && apt-get install -y iptables ipvsadm iproute2 inetutils-ping fping tcpdump && 
        iptables -t nat -A POSTROUTING -o eth0 --dst 10.240.216.73 -m ipvs --ipvs --vaddr 172.18.0.105 --vport 36412 --vmethod masq -j SNAT --to-source 172.18.0.105 && 
        iptables -t nat -A POSTROUTING -o eth0 --dst 10.240.216.74 -m ipvs --ipvs --vaddr 172.18.0.105 --vport 36412 --vmethod masq -j SNAT --to-source 172.18.0.105 &&        
        bash /root/ipvs.sh"
      volumes:
      - ./ipvs-config/ipvs.sh:/root/ipvs.sh
      networks:
        default:
          ipv4_address: 172.18.0.105
  srsran:
      container_name: "srsran"
      image: registry.gitlab.com/infinitydon/registry/srslte:latest
      tty: true
      privileged: true
      command: >
        sh -c  "ip route add 10.240.0.0/16 via 172.18.0.105 && bash"      
      volumes:
      - ./srsLTE-config/enb/enb.conf:/srsLTE/build/srsenb/src/enb.conf
      - ./srsLTE-config/enb/drb.conf:/srsLTE/build/srsenb/src/drb.conf
      - ./srsLTE-config/enb/rr.conf:/srsLTE/build/srsenb/src/rr.conf
      - ./srsLTE-config/enb/sib.conf:/srsLTE/build/srsenb/src/sib.conf
      - ./srsLTE-config/ue/ue.conf:/srsLTE/build/srsenb/src/ue.conf
      depends_on:
      - mme-lb
      networks:
          default:
              ipv4_address: 172.18.0.104

networks:
  default:
    name: kind
    external: true              